### PR TITLE
feat(design): add new assets

### PR DESCRIPTION
**Pull request by elettronelibero**
I exported the needed images in the requested colors (or gradients) and also in a transparent version to ensure freedom of choice by the implementation.
I rasterized the Icons to PNGs in 3 different density ranges and saved them also as SVG.
Furthermore I provided the Sketch design resource.

I can reduce the SVG Size up to 1/3 ... before that please test with the following stock and report change-requests

`            © Luca Marzano [elettronelibero] - Handcrafted with L❤︎VE          `

### CODE REVIEW

**Comment by FrecksterGIT** [comment]
Ok, lets keep working on integration in this branch.
So far I got it all working. I used the transparent SVGs for the objectives and the 3 colored versions for bloodlust.

Changed some double ids (gradient and filter) in the bloodlust icons.

I'm using the icons directly from the assets folder using webpack-raw-loader:
`import campTemplate from '../../assets/gw2_wvw_map-vector--camp_transparent.svg';`

That means icons should all have unique ids and no xml-headers and stuff.

**Comment by FrecksterGIT** [comment]
Assets in use atm:

```javascript
import campTemplate from '../../assets/gw2_wvw_map-vector--camp_transparent.svg';
import towerTemplate from '../../assets/gw2_wvw_map-vector--tower_transparent.svg';
import keepTemplate from '../../assets/gw2_wvw_map-vector--keep_transparent.svg';
import castleTemplate from '../../assets/gw2_wvw_map-vector--castle_transparent.svg';

import bloodlustRed from '../../assets/gw2_wvw_map-vector--bloodlust_red.svg';
import bloodlustBlue from '../../assets/gw2_wvw_map-vector--bloodlust_blue.svg';
import bloodlustGreen from '../../assets/gw2_wvw_map-vector--bloodlust_green.svg';
```

**Comment by elettronelibero** [comment]
I guess that i can remove all unused png and svg from the assets and 
refactor/make smaller the code for: 
camp/tower/keep/castle transparent svg
and for bl_red-green-blue svg

Please confirm for me to proceed

**Comment by FrecksterGIT** [comment]
Sound good. And could you also move the assets folder out of public to /src/assets? The files are becoming part of the webpack bundle.

**Comment by elettronelibero** [comment]
All done,

please test and merge accordingly

**Comment by elettronelibero** [comment]
Btw. I removed the svg filter (drop shadow) of the bloodlust icons

**Pull request merged**
